# Run parameters
SCREAM_RUN_NAME=scream_dpxx_RICO_50x50
RADTRAN_RUN_NAME=test

# Machine-specific DP-SCREAMXX directories - Abbreviated to SCREAM
SCREAM_DATA_DIR=/projects/ml3drt/dpxx # DP-SCREAMXX output parent directory
SCREAM_RUN_DIR=${SCREAM_DATA_DIR}/${SCREAM_RUN_NAME}/run
SCREAM_OUTPUT_FILE_BASE=scream.INSTANT.nhours_x1.2004-12-16-00000
SCREAM_OUTPUT_FILE_PATH=${SCREAM_RUN_DIR}/${SCREAM_RUN_NAME}.${SCREAM_OUTPUT_FILE_BASE}.nc
SCREAM_OUTPUT_FILE_PATH=/projects/ml3drt/dpxx/scream_dpxx_RICO_50x50_extraDiag/run/scream_dpxx_RICO_50x50.scream.INSTANT.nhours_x1.2004-12-16-00000.nc

# Machine-specific RTE-RRTMGP-CPP I/O directories - Abbreviated to RADTRAN
RADTRAN_DATA_DIR=/projects/ml3drt/rte_rrtmgp_cpp
RADTRAN_RUN_DIR=${RADTRAN_DATA_DIR}/${SCREAM_RUN_NAME}/${RADTRAN_RUN_NAME}
RADTRAN_INPUT_DIR=${RADTRAN_RUN_DIR}/input
RADTRAN_SEPARATE_OUTPUT_DIR=${RADTRAN_RUN_DIR}/separate_output
RADTRAN_COMBINED_OUTPUT_DIR=${RADTRAN_RUN_DIR}/combined_output
RADTRAN_VIZ_DIR=${RADTRAN_RUN_DIR}/viz
RADTRAN_VIZ_INPUT_DIR=${RADTRAN_VIZ_DIR}/input
RADTRAN_FILE_BASE=${SCREAM_RUN_NAME}.${SCREAM_OUTPUT_FILE_BASE}
RADTRAN_INPUT_FILE_PATH_BASE=${RADTRAN_INPUT_DIR}/${RTE_RRTMGP_FILE_BASE}

mkdir -p ${RADTRAN_DATA_DIR}
mkdir -p ${RADTRAN_INPUT_DIR}
mkdir -p ${RADTRAN_SEPARATE_OUTPUT_DIR}
mkdir -p ${RADTRAN_COMBINED_OUTPUT_DIR}
mkdir -p ${RADTRAN_VIZ_DIR}

# RTE-RRTMGP-CPP directories
RTE_RRTMGP_CPP_DIR=$(realpath "../..") # Source directory
RTE_RRTMGP_CPP_BUILD_DIR=${RTE_RRTMGP_CPP_DIR}/build
RTE_RRTMGP_CPP_EXEC=${RTE_RRTMGP_CPP_BUILD_DIR}/test_rte_rrtmgp_rt_gpu
RTE_DATA_DIR=${RTE_RRTMGP_CPP_DIR}/data
RRTMGP_DATA_DIR=${RTE_RRTMGP_CPP_DIR}/rrtmgp-data
SCREAM_DIR=${RTE_RRTMGP_CPP_DIR}/dp_screamxx # DP-SCREAMXX numerical experiment directory
EXPERIMENT_DIR=${SCREAM_DIR}/experiment
EXPERIMENT_ANALYZE_DIR=${EXPERIMENT_DIR}/analysis_tools

# Set Case - for Python Scripts
CASE_NAME="RICO"

#-------------------------------------------------------------------------------
# CHECK DIRECTORIES AND CASE FOR ERRORS
#-------------------------------------------------------------------------------
CURRENT_TIME=$(date +"%T")
echo "[${CURRENT_TIME}]: DEBUGGING - Directories used in script execution:"

echo "RADTRAN_INPUT_DIR: ${RADTRAN_INPUT_DIR}"
echo "RADTRAN_SEPARATE_OUTPUT_DIR: ${RADTRAN_SEPARATE_OUTPUT_DIR}"
echo "RADTRAN_COMBINED_OUTPUT_DIR: ${RADTRAN_SEPARATE_OUTPUT_DIR}"
echo "RADTRAN_VIZ_DIR: ${RADTRAN_VIZ_DIR}"
echo "CASE NAME: ${CASE_NAME}"

#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#CURRENT_TIME=$(date +"%T")
#STAGE_NAME="DP-SCREAM to RTE-RRTMGP-CPP+RT Conversion"
#echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."
#
## Set SZAs, times, and coarsening factors
#SZAS=0,80
#COARSE_FACTORS=1,2,4,8,16
#
#mpirun -np 192 \
#  python ${EXPERIMENT_DIR}/convert-dpscream-output.py \
#    --dp-scream-file ${SCREAM_OUTPUT_FILE_PATH} \
#    --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#    --coarse-factors ${COARSE_FACTORS} \
#    --day-only
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#CURRENT_TIME=$(date +"%T")
#STAGE_NAME="RTE-RRTMGP-CPP+RT Execution"
#echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."
#
#mpirun -np 10 \
#  python ${EXPERIMENT_DIR}/run-rte-rrtmgp-cpp.py \
#    --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#    --rad-tran-outdir ${RADTRAN_SEPARATE_OUTPUT_DIR} \
#    --rad-tran-exec ${RTE_RRTMGP_CPP_EXEC} \
#    --rrtmgp-data-dir ${RRTMGP_DATA_DIR} \
#    --rte-data-dir ${RTE_DATA_DIR} \
#    --raytracing 4096 \
#    --gpus 0,1,2,3,4,5,6,7,8,9
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#CURRENT_TIME=$(date +"%T")
#STAGE_NAME="RTE-RRTMGP-CPP+RT Output Combination"
#echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."
#
#python ${EXPERIMENT_DIR}/combine-rte-rrtmgp-cpp-output.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-separate-outdir ${RADTRAN_SEPARATE_OUTPUT_DIR} \
#  --rad-tran-combined-outdir ${RADTRAN_COMBINED_OUTPUT_DIR}
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
CURRENT_TIME=$(date +"%T")
STAGE_NAME="DP-SCREAM Visualization"
echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: Radiative Transfer Snapshot:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot-dpscream-rad-tran-snapshot.py \
#  --dp-scream-file ${SCREAM_OUTPUT_FILE_PATH} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/rad_tran_snapshot \
#  --detailed-calc true \
#  --zmax 40
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: Atmosphere Snapshot:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot-dpscream-atm-snapshot.py \
#  --dp-scream-file ${SCREAM_OUTPUT_FILE_PATH} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/atm_snapshot \
#  --detailed-calc true \
#  --zmax 40
#
#python ${EXPERIMENT_ANALYZE_DIR}/animate_dp_screamxx_output.py \
#    --dpscream_file_path ${SCREAM_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RADTRAN_VIZ_DIR}
#
#python ${EXPERIMENT_ANALYZE_DIR}/visualize_dp_screamxx_output.py \
#    --dpscream_file_path ${SCREAM_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RADTRAN_VIZ_DIR}
#echo "${STAGE_NAME} complete!"
#
#mpirun -np 32 python ${EXPERIMENT_ANALYZE_DIR}/plot_olr.py \
#    --dpscream_file_path ${SCREAM_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RADTRAN_VIZ_DIR} \
#    --distribution-visualization ribbons
#
#python ${EXPERIMENT_ANALYZE_DIR}/plot_sza.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RADTRAN_INPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RADTRAN_VIZ_DIR}
#
CURRENT_TIME=$(date +"%T")
echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------
CURRENT_TIME=$(date +"%T")
STAGE_NAME="RTE-RRTMGP-CPP+RT INPUT VISUALIZATION"
echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: Volume Mixing Ratio Snapshot:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot-rte-rrtmgp-cpp-vmr-snapshot.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/vmr_snapshot \
#  --zmax 40 \
#  --coarse-factors 16
#
CURRENT_TIME=$(date +"%T")
echo "[${CURRENT_TIME}]: Atmosphere Snapshot:"
python ${EXPERIMENT_ANALYZE_DIR}/plot-rte-rrtmgp-cpp-atm-snapshot.py \
  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/atm_snapshot \
  --zmax 40 \
  --coarse-factors 1
#
#echo "Solar Zenith Angle:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_sza.py \
#  --dp-scream-file ${SCREAM_OUTPUT_FILE_PATH} \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}
#
CURRENT_TIME=$(date +"%T")
echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#CURRENT_TIME=$(date +"%T")
#STAGE_NAME="RTE-RRTMGP-CPP+RT OUTPUT VISUALIZATION"
#echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: Atmosphere Radiative Transfer Snapshot:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot-rte-rrtmgp-cpp-rad-tran-snapshot.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_COMBINED_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/rad_tran_snapshot \
#  --detailed-calc true \
#  --zmax 40
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: Atmosphere Radiative Transfer Z-Profile:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_atm_rad_tran_zprofile.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_COMBINED_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/atm_rad_tran_zprofile \
#  --detailed-calc true \
#  --zmax 16 \
#  --lr 16
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: Surface Radiative Transfer:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_sfc_rad_tran.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_COMBINED_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/sfc_rad_tran \
#  --detailed-calc true \
#  --case ${CASE_NAME} \
#  --lr 1,2,4,8,16
#
#CURRENT_TIME=$(date +"%T")
#echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT ANALYSIS VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

#echo "Radiative Transfer Errors:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_rad_tran_errors.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/rad_tran_errors \
#  --detailed-calc false \
#  --zmax 16 \
#  --case ${CASE_NAME} \
#  --lr 32,64

#echo "Radiative Transfer Distributions:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_rad_tran_dists.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/rad_tran_dists \
#  --detailed-calc true \
#  --zmax 16 \
#  --case ${CASE_NAME} \
#  --lr 64

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------