# Run parameters
export CUDA_VISIBLE_DEVICES=0

# Machine-specific DP-SCREAMXX directories
DP_SCREAMXX_DATA_DIR=/projects/ml3drt/dpxx # DP-SCREAMXX output parent directory
DP_SCREAMXX_RUN_NAME=scream_dpxx_GATEIII_300x300
DP_SCREAMXX_RUN_DIR=${DP_SCREAMXX_DATA_DIR}/${DP_SCREAMXX_RUN_NAME}/run
DP_SCREAMXX_OUTPUT_FILE_BASE=scream.INSTANT.nmins_x15.1974-08-30-00000
DP_SCREAMXX_OUTPUT_FILE_PATH=${DP_SCREAMXX_RUN_DIR}/${DP_SCREAMXX_RUN_NAME}.${DP_SCREAMXX_OUTPUT_FILE_BASE}.nc

# Machine-specific RTE-RRTMGP-CPP I/O directories
RTE_RRTMGP_CPP_DIR=/projects/ml3drt/rte_rrtmgp_cpp
RTE_RRTMGP_CPP_RUN_NAME=1974-08-30
RTE_RRTMGP_CPP_RUN_DIR=${RTE_RRTMGP_CPP_DIR}/${DP_SCREAMXX_RUN_NAME}/${RTE_RRTMGP_CPP_RUN_NAME}
RTE_RRTMGP_CPP_INPUT_DIR=${RTE_RRTMGP_CPP_RUN_DIR}/input
RTE_RRTMGP_CPP_OUTPUT_DIR=${RTE_RRTMGP_CPP_RUN_DIR}/output
RTE_RRTMGP_CPP_VIZ_DIR=${RTE_RRTMGP_CPP_RUN_DIR}/viz
RTE_RRTMGP_CPP_VIZ_INPUT_DIR=${RTE_RRTMGP_CPP_VIZ_DIR}/input
RTE_RRTMGP_CPP_FILE_BASE=${DP_SCREAMXX_RUN_NAME}.${DP_SCREAMXX_OUTPUT_FILE_BASE}
RTE_RRTMGP_CPP_INPUT_FILE_PATH_BASE=${RTE_RRTMGP_CPP_INPUT_DIR}/${RTE_RRTMGP_FILE_BASE}

mkdir -p ${RTE_RRTMGP_CPP_DIR}
mkdir -p ${RTE_RRTMGP_CPP_INPUT_DIR}
mkdir -p ${RTE_RRTMGP_CPP_OUTPUT_DIR}
mkdir -p ${RTE_RRTMGP_CPP_VIZ_DIR}

# RTE-RRTMGP-CPP directories
RTE_RRTMGP_CPP_DIR=$(realpath "../..") # Source directory
RTE_RRTMGP_CPP_BUILD_DIR=${RTE_RRTMGP_CPP_DIR}/build
RTE_DATA_DIR=${RTE_RRTMGP_CPP_DIR}/data
RRTMGP_DATA_DIR=${RTE_RRTMGP_CPP_DIR}/rrtmgp-data
DP_SCREAMXX_DIR=${RTE_RRTMGP_CPP_DIR}/dp_screamxx # DP-SCREAMXX numerical experiment directory
EXPERIMENT_DIR=${DP_SCREAMXX_DIR}/experiment
EXPERIMENT_ANALYZE_DIR=${EXPERIMENT_DIR}/analyze_utils

# Link RRTMGP files
ln -sf ${RRTMGP_DATA_DIR}/rrtmgp-clouds-sw.nc cloud_coefficients_sw.nc
ln -sf ${RRTMGP_DATA_DIR}/rrtmgp-clouds-lw.nc cloud_coefficients_lw.nc
ln -sf ${RRTMGP_DATA_DIR}/rrtmgp-gas-sw-g224.nc coefficients_sw.nc
ln -sf ${RRTMGP_DATA_DIR}/rrtmgp-gas-lw-g256.nc coefficients_lw.nc
ln -sf ${RTE_DATA_DIR}/aerosol_optics.nc

# Set SZAs, times, and coarsening factors
SZAS_PYTHON="[]"
COARSE_FACTORS_PYTHON="[1, 2, 4, 8, 16, 32, 64]"

echo "RTE_RRTMGP_CPP_INPUT_DIR: ${RTE_RRTMGP_CPP_INPUT_DIR}"
echo "RTE_RRTMGP_CPP_OUTPUT_DIR: ${RTE_RRTMGP_CPP_OUTPUT_DIR}"
echo "RTE_RRTMGP_CPP_VIZ_DIR: ${RTE_RRTMGP_CPP_VIZ_DIR}"

#-------------------------------------------------------------------------------
#STAGE_NAME="DP-SCREAM to RTE-RRTMGP-CPP+RT Conversion"
#echo "Beginning ${STAGE_NAME}..."

#mpirun -np 256 \
#  python ${EXPERIMENT_DIR}/convert_dp_screamxx_output.py \
#    --dpscream_file_path ${DP_SCREAMXX_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --coarse_factors "${COARSE_FACTORS_PYTHON}"

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT Execution"
#echo "Beginning ${STAGE_NAME}..."

#python run_rte_rrtmgp_cpp_timeslices_multi_gpu_new.py \
#  --rte-rrtmgp-cpp-input-dir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rte-rrtmgp-cpp-executable-dir ${RTE_RRTMGP_CPP_BUILD_DIR} \
#  --rte-rrtmgp-cpp-output-dir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rrtmgp-data-dir ${RRTMGP_DATA_DIR} \
#  --rte-data-dir ${RTE_DATA_DIR} \
#  --work-dir ${RTE_RRTMGP_CPP_INPUT_DIR}/.rte_rrtmgp_work \
#  --raytracing 16384 \
#  --gpus "[3,4,5,6,7,8,9,10,11,12,13,14,15]" \
#  --missing-output-list /ascldap/users/jltorch/codes/rte-rrtmgp-cpp/jasonltorchinsky/timeseries-analysis/dp_screamxx/jobscripts/missing_files.txt

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#STAGE_NAME="DP-SCREAM Visualization"
#echo "Beginning ${STAGE_NAME}..."
#python ${EXPERIMENT_ANALYZE_DIR}/animate_dp_screamxx_output.py \
#    --dpscream_file_path ${DP_SCREAMXX_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}
#
#python ${EXPERIMENT_ANALYZE_DIR}/visualize_dp_screamxx_output.py \
#    --dpscream_file_path ${DP_SCREAMXX_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}
#echo "${STAGE_NAME} complete!"

#STAGE_NAME="Input Visualization"
#echo "Beginning ${STAGE_NAME}..."
#mpirun -np 8 python ${EXPERIMENT_ANALYZE_DIR}/plot_input.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}

#mpirun -np 32 python ${EXPERIMENT_ANALYZE_DIR}/plot_olr.py \
#    --dpscream_file_path ${DP_SCREAMXX_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR} \
#    --distribution-visualization ribbons

#python ${EXPERIMENT_ANALYZE_DIR}/plot_sza.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}

#echo "${STAGE_NAME} complete!"

#STAGE_NAME="Output Visualization"
#echo "Beginning ${STAGE_NAME}..."
#mpirun -np 8 python ${EXPERIMENT_ANALYZE_DIR}/plot_output.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_output_dir_path ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}
#echo "${STAGE_NAME} complete!"

#STAGE_NAME="Comparison Visualization"
#echo "Beginning ${STAGE_NAME}..."
#mpirun -np 8 python ${EXPERIMENT_ANALYZE_DIR}/plot_comparison.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_output_dir_path ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}

#mpirun -np 16 python ${EXPERIMENT_ANALYZE_DIR}/plot_flux_abs.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_output_dir_path ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}/flux_abs \
#    --zmax 16 #\
#    #--lr 64

#mpirun -np 16 python ${EXPERIMENT_ANALYZE_DIR}/plot_dn_sfc_flux.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_output_dir_path ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}/dn_sfc_flux #\
#    #--lr 64

#echo "${STAGE_NAME} complete!"

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT OUTPUT VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

#echo "Absorbed Flux:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_atm_heating.py \
#  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/abs_flux \
#  --detailed-calc true \
#  --zmax 16 \
#  --yslice 132.5 \
#  --lr 64

#echo "Net Surface Flux:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_sfc_heating.py \
#  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/net_sfc_flux \
#  --detailed-calc true \
#  --lr 64

#echo "Atmospheric Heating Rates:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_atm_heating_new.py \
#  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/atm_heating \
#  --detailed-calc true \
#  --zmax 16 \
#  --yslice 132.5 \
#  --case GATEIII \
#  --lr 64

#echo "Surface Heating Rates:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_sfc_heating.py \
#  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/sfc_heating \
#  --case GATEIII \
#  --detailed-calc true \
#  --lr 64

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT ANALYSIS VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

#echo "Error:"
#mpirun -np 32 \
# python ${EXPERIMENT_ANALYZE_DIR}/plot_error.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_output_dir_path ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}/error \
#    --error-type rmse,mae,mbe \
#    --zmax 16 \
#    --lr 32,64

echo "Radiative Distributions:"
#mpirun -np 32 \
# python ${EXPERIMENT_ANALYZE_DIR}/plot_radiative_distributions.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_output_dir_path ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR}/radiative_distributions \
#    --distribution-visualization ribbons \
#    --zmax 16 \
#    --case GATEIII \
#    --lr 64

python ${EXPERIMENT_ANALYZE_DIR}/plot_radiative_distributions_new.py \
  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/radiative_distributions \
  --detailed-calc true \
  --zmax 16 \
  --yslice 132.5 \
  --case GATEIII \
  --lr 64

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------