#!/bin/bash
#SBATCH --time=0-02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --account=fy260144
#SBATCH --reservation=flight-cldera
#SBATCH --job-name=1974-08-30
#SBATCH --output=%j.out
#SBATCH --error=%j.err

# Machine-specific DP-SCREAMXX directories
DP_SCREAMXX_DATA_DIR=/pscratch/jltorch/ml3drt/dpxx # DP-SCREAMXX output parent directory
DP_SCREAMXX_RUN_NAME=scream_dpxx_GATEIII_300x300
DP_SCREAMXX_RUN_DIR=${DP_SCREAMXX_DATA_DIR}/${DP_SCREAMXX_RUN_NAME}/run
DP_SCREAMXX_OUTPUT_FILE_BASE=scream.INSTANT.nmins_x15.1974-08-30-00000
DP_SCREAMXX_OUTPUT_FILE_PATH=${DP_SCREAMXX_RUN_DIR}/${DP_SCREAMXX_RUN_NAME}.${DP_SCREAMXX_OUTPUT_FILE_BASE}.nc

# Machine-specific RTE-RRTMGP-CPP I/O directories
RTE_RRTMGP_CPP_DIR=/pscratch/jltorch/ml3drt/rte-rrtmgp-cpp
RTE_RRTMGP_CPP_RUN_NAME=1974-08-30
RTE_RRTMGP_CPP_RUN_DIR=${RTE_RRTMGP_CPP_DIR}/${DP_SCREAMXX_RUN_NAME}/${RTE_RRTMGP_CPP_RUN_NAME}
RTE_RRTMGP_CPP_INPUT_DIR=${RTE_RRTMGP_CPP_RUN_DIR}/input
RTE_RRTMGP_CPP_OUTPUT_DIR=${RTE_RRTMGP_CPP_RUN_DIR}/output
RTE_RRTMGP_CPP_VIZ_DIR=${RTE_RRTMGP_CPP_RUN_DIR}/viz
RTE_RRTMGP_CPP_VIZ_INPUT_DIR=${RTE_RRTMGP_CPP_VIZ_DIR}/input
RTE_RRTMGP_CPP_FILE_BASE=${DP_SCREAMXX_RUN_NAME}.${DP_SCREAMXX_OUTPUT_FILE_BASE}
RTE_RRTMGP_CPP_INPUT_FILE_PATH_BASE=${RTE_RRTMGP_CPP_INPUT_DIR}/${RTE_RRTMGP_CPP_FILE_BASE}

mkdir -p ${RTE_RRTMGP_CPP_DIR}
mkdir -p ${RTE_RRTMGP_CPP_INPUT_DIR}
mkdir -p ${RTE_RRTMGP_CPP_OUTPUT_DIR}
mkdir -p ${RTE_RRTMGP_CPP_VIZ_DIR}

# RTE-RRTMGP-CPP directories
RTE_RRTMGP_CPP_DIR=$(realpath "../..") # Source directory
DP_SCREAMXX_DIR=${RTE_RRTMGP_CPP_DIR}/dp_screamxx # DP-SCREAMXX numerical experiment directory
EXPERIMENT_DIR=${DP_SCREAMXX_DIR}/experiment
EXPERIMENT_ANALYZE_DIR=${EXPERIMENT_DIR}/analyze_utils

# Set Case - for Python Scripts
CASE_NAME="GATEIII"

#-------------------------------------------------------------------------------
# CHECK DIRECTORIES AND CASE FOR ERRORS

echo "RTE_RRTMGP_CPP_INPUT_DIR: ${RTE_RRTMGP_CPP_INPUT_DIR}"
echo "RTE_RRTMGP_CPP_OUTPUT_DIR: ${RTE_RRTMGP_CPP_OUTPUT_DIR}"
echo "RTE_RRTMGP_CPP_VIZ_DIR: ${RTE_RRTMGP_CPP_VIZ_DIR}"
echo "CASE NAME: ${CASE_NAME}"

#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="DP-SCREAM OUTPUT VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

#echo "OLR:"
#srun --mpi=pmi2 -n ${SLURM_NTASKS} \
#  python ${EXPERIMENT_ANALYZE_DIR}/plot_olr.py \
#    --dpscream_file_path ${DP_SCREAMXX_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_CPP_VIZ_DIR} \
#    --distribution-visualization ribbons

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="DP-SCREAM to RTE-RRTMGP-CPP+RT Conversion"
#echo "Beginning ${STAGE_NAME}..."

# Set SZAs, times, and coarsening factors
#SZAS_PYTHON="[]"
#COARSE_FACTORS_PYTHON="[1, 2, 4, 8, 16, 32, 64]"

#srun --mpi=pmi2 -n ${SLURM_NTASKS} \
#  python ${EXPERIMENT_DIR}/convert_dp_screamxx_output.py \
#    --dpscream_file_path ${DP_SCREAMXX_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_dir_path ${RTE_RRTMGP_CPP_INPUT_DIR} \
#    --coarse_factors "${COARSE_FACTORS_PYTHON}"

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT Combination"
#echo "Beginning ${STAGE_NAME}..."
#
#SEPARATE_DIR=${RTE_RRTMGP_CPP_RUN_DIR}/separate_output
#COMBINED_DIR=${RTE_RRTMGP_CPP_RUN_DIR}/output
#
#echo "SEPARATE_DIR: ${SEPARATE_DIR}"
#echo "COMBINED_DIR: ${COMBINED_DIR}"
#echo "DP_SCREAM FILE: ${DP_SCREAMXX_OUTPUT_FILE_PATH}"
#
#srun --mpi=pmi2 -n ${SLURM_NTASKS} \
#  python ${EXPERIMENT_DIR}/combine_rte_rrtmgp_cpp_files.py \
#    --input-dir ${SEPARATE_DIR} \
#    --output-dir ${COMBINED_DIR} \
#    --dpscream-file ${DP_SCREAMXX_OUTPUT_FILE_PATH} \
#    --kind out \
#    --engine netcdf4 \
#    --scheduler single-threaded \
#    --replace-existing \
#    --lock-writes \
#    --keep-t-index \
#    --time-chunk 1 \
#    --xy-chunk 300
#
#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT INPUT VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."
#
#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT OUTPUT VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

echo "Atmosphere Radiative Transfer Snapshot:"
python ${EXPERIMENT_ANALYZE_DIR}/plot_atm_rad_tran_snapshot.py \
  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/atm_rad_tran_snapshot \
  --detailed-calc true \
  --zmax 16

#echo "Atmosphere Radiative Transfer Z-Profile:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_atm_rad_tran_zprofile.py \
#  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/atm_rad_tran_zprofile \
#  --detailed-calc true \
#  --zmax 16

#echo "Surface Radiative Transfer:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_sfc_rad_tran.py \
#  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/sfc_rad_tran \
#  --detailed-calc true \
#  --case ${CASE_NAME}

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT ANALYSIS VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

#echo "Radiative Transfer Errors:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_rad_tran_errors.py \
#  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/rad_tran_errors \
#  --detailed-calc true \
#  --zmax 16 \
#  --case ${CASE_NAME}

#echo "Radiative Distributions:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_rad_tran_dists.py \
#  --rad-tran-indir ${RTE_RRTMGP_CPP_INPUT_DIR} \
#  --rad-tran-outdir ${RTE_RRTMGP_CPP_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RTE_RRTMGP_CPP_VIZ_DIR}/rad_tran_dists \
#  --detailed-calc true \
#  --zmax 16 \
#  --case ${CASE_NAME}

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------