#!/bin/bash
#SBATCH --time=2-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --account=fy260144
#SBATCH --reservation=flight-cldera
#SBATCH --job-name=debug-1974-08-30
#SBATCH --output=%j.out
#SBATCH --error=%j.err

export HDF5_USE_FILE_LOCKING=FALSE

# Run parameters
SCREAM_RUN_NAME=scream_dpxx_GATEIII_300x300_corrupt
RADTRAN_RUN_NAME=debug-1974-08-30

# Machine-specific DP-SCREAMXX directories - Abbereviated to SCREAM
SCREAM_DATA_DIR=/pscratch/jltorch/ml3drt/dpxx # DP-SCREAMXX output parent directory
SCREAM_RUN_DIR=${SCREAM_DATA_DIR}/${SCREAM_RUN_NAME}/run
SCREAM_OUTPUT_FILE_BASE=scream.INSTANT.nmins_x15.1974-08-30-00000
SCREAM_OUTPUT_FILE_PATH=${SCREAM_RUN_DIR}/${SCREAM_RUN_NAME}.${SCREAM_OUTPUT_FILE_BASE}.nc
SCREAM_OUTPUT_FILE_PATH=/projects/ml3drt/dpxx/scream_dpxx_GATEIII_300x300_corrupt/run/scream_dpxx_GATEIII_300x300.scream.INSTANT.nmins_x15.1974-08-30-00000.nc

# Machine-specific RTE-RRTMGP-CPP I/O directories - Abbreviated to RADTRAN
RADTRAN_DATA_DIR=/pscratch/jltorch/ml3drt/rte-rrtmgp-cpp
RADTRAN_RUN_DIR=${RADTRAN_DATA_DIR}/${SCREAM_RUN_NAME}/${RADTRAN_RUN_NAME}
RADTRAN_SEPARATE_INPUT_DIR=${RADTRAN_RUN_DIR}/separate_input
RADTRAN_COMBINED_INPUT_DIR=${RADTRAN_RUN_DIR}/combined_input
RADTRAN_SEPARATE_OUTPUT_DIR=${RADTRAN_RUN_DIR}/separate_output
RADTRAN_COMBINED_OUTPUT_DIR=${RADTRAN_RUN_DIR}/combined_output
RADTRAN_VIZ_DIR=${RADTRAN_RUN_DIR}/viz
RADTRAN_VIZ_INPUT_DIR=${RADTRAN_VIZ_DIR}/input
RADTRAN_FILE_BASE=${SCREAM_RUN_NAME}.${SCREAM_OUTPUT_FILE_BASE}
RADTRAN_INPUT_FILE_PATH_BASE=${RADTRAN_INPUT_DIR}/${RADTRAN_FILE_BASE}

mkdir -p ${RADTRAN_DATA_DIR}
mkdir -p ${RADTRAN_SEPARATE_INPUT_DIR}
mkdir -p ${RADTRAN_COMBINED_INPUT_DIR}
mkdir -p ${RADTRAN_SEPARATE_OUTPUT_DIR}
mkdir -p ${RADTRAN_COMBINED_OUTPUT_DIR}
mkdir -p ${RADTRAN_VIZ_DIR}

# RTE-RRTMGP-CPP directories
RTE_RRTMGP_CPP_DIR=/ascldap/users/jltorch/codes/rte-rrtmgp-cpp/jasonltorchinsky/dpscream-output-conversion # Source directory
SCREAM_DIR=${RTE_RRTMGP_CPP_DIR}/dp_screamxx # DP-SCREAMXX numerical experiment directory
EXPERIMENT_DIR=${SCREAM_DIR}/experiment
EXPERIMENT_ANALYZE_DIR=${EXPERIMENT_DIR}/analysis_tools

# Set Case - for Python Scripts
CASE_NAME="GATEIII"

#-------------------------------------------------------------------------------
# CHECK DIRECTORIES AND CASE FOR ERRORS
#-------------------------------------------------------------------------------
CURRENT_TIME=$(date +"%T")
echo "[${CURRENT_TIME}]: DEBUGGING - Directories used in script execution:"

echo "RADTRAN_SEPARATE_INPUT_DIR: ${RADTRAN_SEPARATE_INPUT_DIR}"
echo "RADTRAN_COMBINED_INPUT_DIR: ${RADTRAN_COMBINED_INPUT_DIR}"
echo "RADTRAN_SEPARATE_OUTPUT_DIR: ${RADTRAN_SEPARATE_OUTPUT_DIR}"
echo "RADTRAN_COMBINED_OUTPUT_DIR: ${RADTRAN_COMBINED_OUTPUT_DIR}"
echo "RADTRAN_VIZ_DIR: ${RADTRAN_VIZ_DIR}"
echo "CASE NAME: ${CASE_NAME}"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# CURRENT_TIME=$(date +"%T")
# STAGE_NAME="DP-SCREAM to RTE-RRTMGP-CPP+RT Conversion"
# echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."

# # Set SZAs, times, and coarsening factors
# COARSE_FACTORS=1,2,4,8,16,32,64

# srun --mpi=pmi2 -n ${SLURM_NTASKS} \
#   python ${EXPERIMENT_DIR}/convert-dpscream-output.py \
#     --dp-scream-file ${SCREAM_OUTPUT_FILE_PATH} \
#     --rad-tran-indir ${RADTRAN_SEPARATE_INPUT_DIR} \
#     --coarse-factors ${COARSE_FACTORS} \
#     --day-only

# CURRENT_TIME=$(date +"%T")
# echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# CURRENT_TIME=$(date +"%T")
# STAGE_NAME="RTE-RRTMGP-CPP+RT Input Combination"
# echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."

# # Set coarsening factors
# COARSE_FACTORS=1,2,4,8,16,32,64

# python ${EXPERIMENT_DIR}/combine-rte-rrtmgp-cpp-input.py \
#   --rad-tran-separate-indir ${RADTRAN_SEPARATE_INPUT_DIR} \
#   --rad-tran-combined-indir ${RADTRAN_COMBINED_INPUT_DIR} \
#   --coarse-factors ${COARSE_FACTORS}

# CURRENT_TIME=$(date +"%T")
# echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

## Flight is not a GPU-enbaled machine
## Move combined input files to a GPU-enabled machine
## Run ray-traver on GPU-enabled machine
## Move separate output files back to Flight for further processing

#-------------------------------------------------------------------------------
CURRENT_TIME=$(date +"%T")
STAGE_NAME="RTE-RRTMGP-CPP+RT Output Combination"
echo "[${CURRENT_TIME}]: Beginning ${STAGE_NAME}..."

# Set coarsening factors
COARSE_FACTORS=2

python ${EXPERIMENT_DIR}/combine-rte-rrtmgp-cpp-output.py \
  --rad-tran-combined-indir ${RADTRAN_COMBINED_INPUT_DIR} \
  --rad-tran-separate-outdir ${RADTRAN_SEPARATE_OUTPUT_DIR} \
  --rad-tran-combined-outdir ${RADTRAN_COMBINED_OUTPUT_DIR} \
  --coarse-factors ${COARSE_FACTORS}

CURRENT_TIME=$(date +"%T")
echo "[${CURRENT_TIME}]: ${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="DP-SCREAM OUTPUT VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

#echo "OLR:"
#srun --mpi=pmi2 -n ${SLURM_NTASKS} \
#  python ${EXPERIMENT_ANALYZE_DIR}/plot_olr.py \
#    --dpscream_file_path ${SCREAM_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RADTRAN_VIZ_DIR} \
#    --distribution-visualization ribbons

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT INPUT VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."
#
#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT OUTPUT VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

#echo "Atmosphere Radiative Transfer Snapshot:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_atm_rad_tran_snapshot.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/atm_rad_tran_snapshot \
#  --detailed-calc true \
#  --zmax 16

#echo "Atmosphere Radiative Transfer Z-Profile:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_atm_rad_tran_zprofile.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/atm_rad_tran_zprofile \
#  --detailed-calc true \
#  --zmax 16

#echo "Surface Radiative Transfer:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_sfc_rad_tran.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/sfc_rad_tran \
#  --detailed-calc true \
#  --case ${CASE_NAME}

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#STAGE_NAME="RTE-RRTMGP-CPP+RT ANALYSIS VISUALIZATION"
#echo "Beginning ${STAGE_NAME}..."

#echo "Radiative Transfer Errors:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_rad_tran_errors.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/rad_tran_errors \
#  --detailed-calc true \
#  --zmax 16 \
#  --case ${CASE_NAME}

#echo "Radiative Distributions:"
#python ${EXPERIMENT_ANALYZE_DIR}/plot_rad_tran_dists.py \
#  --rad-tran-indir ${RADTRAN_INPUT_DIR} \
#  --rad-tran-outdir ${RADTRAN_OUTPUT_DIR} \
#  --rad-tran-vizdir ${RADTRAN_VIZ_DIR}/rad_tran_dists \
#  --detailed-calc true \
#  --zmax 16 \
#  --case ${CASE_NAME}

#echo "${STAGE_NAME} complete!"
#-------------------------------------------------------------------------------