#!/bin/bash
#SBATCH --nodes=1
#SBATCH --time=00:02:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --gpus=1
#SBATCH --gpus-per-node=1
#SBATCH --constraint=gpu
#SBATCH --qos=debug
#SBATCH --account=m4815
#SBATCH --job-name=rcemip
#SBATCH --output=%j.out
#SBATCH --error=%j.err

# Flags:
# --shortwave          DEFAULT[True]  : Enable computation of shortwave radiation.
# --longwave           DEFAULT[False] : Enable computation of longwave radiation.
# --fluxes             DEFAULT[True]  : Enable computation of fluxes.
# --two-stream         DEFAULT[True]  : Run two-stream solver to obtain 1D fluxes.
# --raytracing         DEFAULT[32]    : Ray tracer rays-per pixel. '--raytracing False' to turn off.
# --independent-column DEFAULT[False] : Run ray tracer in independent column mode.
# --cloud-optics       DEFAULT[False] : Enable cloud optics (both liquid and ice).
# --liq-cloud-optics   DEFAULT[False] : Liquid only cloud optics.
# --ice-cloud-optics   DEFAULT[False] : Ice only cloud optics.
# --cloud-mie          DEFAULT[False] : Use Mie tables for cloud scattering in ray tracer.
# --aerosol-optics     DEFAULT[False] : Enable aerosol optics.
# --single-gpt         DEFAULT[False] : Output optical properties and fluxes for a single g-point. '--single-gpt 100': output 100th g-point.
# --profiling          DEFAULT[False] : Perform additional profiling run.
# --delta-cloud        DEFAULT[False] : Delta-scaling of cloud optical properties.
# --delta-aerosol      DEFAULT[False] : Delta-scaling of aerosol optical properties.
# --tica               DEFAULT[False] : Attenuate path when doing an overhead 1D calculation of tilted input.

../build/test_rte_rrtmgp_rt_gpu
