# Standard Library Imports

# Third-Party Library Imports

# Local Library Imports

grid_dimensions: dict = {
    "ngrid_x" : (),
    "ngrid_y" : (),
    "ngrid_z" : (),
    "x" : "x",
    "y" : "y",
    "z" : "z",
    "xh" : "xh",
    "yh" : "yh",
    "zh" : "zh",
    "z_lay" : ("lay"),
    "z_lev" : ("lev"),
}

grid_descriptions: dict = {
    "ngrid_x" : "Number of Acceleration-Grid Points - x-dimension",
    "ngrid_y" : "Number of Acceleration-Grid Points - y-dimension",
    "ngrid_z" : "Number of Acceleration-Grid Points - z-dimension",
    "x" : "Column Midpoints - x-dimension",
    "y" : "Column Midpoints - y-dimension",
    "z" : "Layer Midpoints",
    "xh" : "Column Interfaces - x-dimension",
    "yh" : "Column Interfaces - y-dimension",
    "zh" : "Layer Interfaces",
    "z_lay" : "Layer Midpoints",
    "z_lev" : "Layer Interfaces",
}

grid_units: dict = {
    "ngrid_x" : "",
    "ngrid_y" : "",
    "ngrid_z" : "",
    "x" : "m",
    "y" : "m",
    "z" : "m",
    "xh" : "m",
    "yh" : "m",
    "zh" : "m",
    "z_lay" : "m",
    "z_lev" : "m",
}

fields_dimensions: dict = {
    "p_lay" : ("lay", "y", "x"),
    "p_lev" : ("lev", "y", "x"),
    "t_lay" : ("lay", "y", "x"),
    "t_lev" : ("lev", "y", "x"),
    "rh" : ("lay", "y", "x"),
    "lwp" : ("lay", "y", "x"),
    "iwp" : ("lay", "y", "x"),
    "rel" : ("lay", "y", "x"),
    "dei" : ("lay", "y", "x"),
    "vmr_co2"     : ("lay", "y", "x"),
    "vmr_ch4"     : ("lay", "y", "x"),
    "vmr_n2o"     : ("lay", "y", "x"),
    "vmr_o3"      : ("lay", "y", "x"),
    "vmr_h2o"     : ("lay", "y", "x"),
    "vmr_n2"      : ("lay", "y", "x"),
    "vmr_o2"      : ("lay", "y", "x"),
    "vmr_co"      : ("lay", "y", "x"),
    "vmr_ccl4"    : ("lay", "y", "x"),
    "vmr_cfc11"   : ("lay", "y", "x"),
    "vmr_cfc12"   : ("lay", "y", "x"),
    "vmr_cfc22"   : ("lay", "y", "x"),
    "vmr_hfc143a" : ("lay", "y", "x"),
    "vmr_hfc125"  : ("lay", "y", "x"),
    "vmr_hfc23"   : ("lay", "y", "x"),
    "vmr_hfc32"   : ("lay", "y", "x"),
    "vmr_hfc134a" : ("lay", "y", "x"),
    "vmr_cf4"     : ("lay", "y", "x"),
    "vmr_no2"     : ("lay", "y", "x"),
    "aermr01" : ("lay", "y", "x"),
    "aermr02" : ("lay", "y", "x"),
    "aermr03" : ("lay", "y", "x"),
    "aermr04" : ("lay", "y", "x"),
    "aermr05" : ("lay", "y", "x"),
    "aermr06" : ("lay", "y", "x"),
    "aermr07" : ("lay", "y", "x"),
    "aermr08" : ("lay", "y", "x"),
    "aermr09" : ("lay", "y", "x"),
    "aermr10" : ("lay", "y", "x"),
    "aermr11" : ("lay", "y", "x"),
    "emis_sfc" : ("y", "x", "band_lw"),
    "t_sfc" : ("y", "x"),
    "sfc_alb_dir" : ("y", "x", "band_sw"),
    "sfc_alb_dif" : ("y", "x", "band_sw"),
    "tsi" : ("y", "x"),
    "mu0" : ("y", "x"),
    "azi" : ("y", "x"),
}

fields_descriptions: dict = {
    "p_lay" : "Pressure - layer midpoints",
    "p_lev" : "Pressure - layer interfaces",
    "t_lay" : "Temperature - layer midpoints",
    "t_lev" : "Temperature - layer interfaces",
    "rh" : "Relative Humidity - layer midpoints",
    "lwp" : "Liquid Water Path - layer midpoints",
    "iwp" : "Ice Water Path - layer midpoints",
    "rel" : "Liquid Water Effective Radius - layer midpoints",
    "dei" : "Ice Water Effective Diameter - layer midpoints",
    "vmr_co2"     : "Volume Mixing Ratio - Carbon Dioxide (CO2)", 
    "vmr_ch4"     : "Volume Mixing Ratio - Methane (CH4)", 
    "vmr_n2o"     : "Volume Mixing Ratio - Nitrous Oxide (N2O)", 
    "vmr_o3"      : "Volume Mixing Ratio - Ozone (O3)", 
    "vmr_h2o"     : "Volume Mixing Ratio - Water Vapor (H2O)", 
    "vmr_n2"      : "Volume Mixing Ratio - Nitrogen (N2)", 
    "vmr_o2"      : "Volume Mixing Ratio - Oxygen (O2)", 
    "vmr_co"      : "Volume Mixing Ratio - Carbon Monoxide (CO)", 
    "vmr_ccl4"    : "Volume Mixing Ratio - Carbon Tertachloride (CCl4)", 
    "vmr_cfc11"   : "Volume Mixing Ratio - Trichlorofluoromethane (CFC-11)", 
    "vmr_cfc12"   : "Volume Mixing Ratio - Dichlorodifluoromethane (CFC-12)", 
    "vmr_cfc22"   : "Volume Mixing Ratio - Chlorodifluoromethane (CFC-22)", 
    "vmr_hfc143a" : "Volume Mixing Ratio - 1,1,1-Trifluoroethane (HFC-143a)", 
    "vmr_hfc125"  : "Volume Mixing Ratio - Pentafluoroethane (HFC-125)", 
    "vmr_hfc23"   : "Volume Mixing Ratio - Trifluoromethane (HFC-23)", 
    "vmr_hfc32"   : "Volume Mixing Ratio - Difluoromethane (HFC-32)", 
    "vmr_hfc134a" : "Volume Mixing Ratio - 1,1,1,2-Tetrafluoroethane (HFC-134a)", 
    "vmr_cf4"     : "Volume Mixing Ratio - Carbon Tetrafluoride (CF4)", 
    "vmr_no2"     : "Volume Mixing Ratio - Nitrogen Dioxide (NO2)",
    "aermr01" : "Aerosol mixing ratio - Sea Salt (0.03 - 0.5 µm)",
    "aermr02" : "Aerosol mixing ratio - Sea Salt (0.5 - 5 µm)",
    "aermr03" : "Aerosol mixing ratio - Sea Salt (5 - 20 µm)",
    "aermr04" : "Aerosol mixing ratio - Dust (0.03 - 0.55 µm)",
    "aermr05" : "Aerosol mixing ratio - Dust (0.55 - 0.9 µm)",
    "aermr06" : "Aerosol mixing ratio - Dust (0.9 - 20 µm)",
    "aermr07" : "Aerosol mixing ratio - Hydrophilic Organic Matter",
    "aermr08" : "Aerosol mixing ratio - Hydrophobic Organic Matter",
    "aermr09" : "Aerosol mixing ratio - Hydrophilic Black Carbon",
    "aermr10" : "Aerosol mixing ratio - Hydrophobic Black Carbon",
    "aermr11" : "Aerosol mixing ratio - Sulphate",
    "emis_sfc" : "Surface Emissivity",
    "t_sfc" : "Surface Temperature",
    "sfc_alb_dir" : "Surface Albedo - Direct",
    "sfc_alb_dif" : "Surface Albedo - Diffuse",
    "tsi" : "Total Solar Irradiance",
    "mu0" : "Cosine of Solar Zenith Angle",
    "azi" : "Azimuthal Angle",
}

fields_units: dict = {
    "p_lay" : "Pa",
    "p_lev" : "Pa",
    "t_lay" : "K",
    "t_lev" : "K",
    "rh" : "Pa Pa^(-1)",
    "vmr_co2"     : "kg kg^(-1)",
    "vmr_ch4"     : "kg kg^(-1)",
    "vmr_n2o"     : "kg kg^(-1)",
    "vmr_o3"      : "kg kg^(-1)",
    "vmr_h2o"     : "kg kg^(-1)",
    "vmr_n2"      : "kg kg^(-1)",
    "vmr_o2"      : "kg kg^(-1)",
    "vmr_co"      : "kg kg^(-1)",
    "vmr_ccl4"    : "kg kg^(-1)",
    "vmr_cfc11"   : "kg kg^(-1)",
    "vmr_cfc12"   : "kg kg^(-1)",
    "vmr_cfc22"   : "kg kg^(-1)",
    "vmr_hfc143a" : "kg kg^(-1)",
    "vmr_hfc125"  : "kg kg^(-1)",
    "vmr_hfc23"   : "kg kg^(-1)",
    "vmr_hfc32"   : "kg kg^(-1)",
    "vmr_hfc134a" : "kg kg^(-1)",
    "vmr_cf4"     : "kg kg^(-1)",
    "vmr_no2"     : "kg kg^(-1)",
    "aermr01" : "kg kg^(-1)",
    "aermr02" : "kg kg^(-1)",
    "aermr03" : "kg kg^(-1)",
    "aermr04" : "kg kg^(-1)",
    "aermr05" : "kg kg^(-1)",
    "aermr06" : "kg kg^(-1)",
    "aermr07" : "kg kg^(-1)",
    "aermr08" : "kg kg^(-1)",
    "aermr09" : "kg kg^(-1)",
    "aermr10" : "kg kg^(-1)",
    "aermr11" : "kg kg^(-1)",
    "emis_sfc" : "N/A",
    "t_sfc" : "K",
    "sfc_alb_dir" : "N/A",
    "sfc_alb_dif" : "N/A",
    "tsi" : "W m^(-2)",
    "mu0" : "N/A",
    "azi" : "Radians",
    "lwp" : "kg m^(-2)",
    "iwp" : "kg m^(-2)",
    "rel" : "μm",
    "dei" : "μm",
}