# Link RRTMGP files
ln -sf ../rrtmgp-data/rrtmgp-clouds-sw.nc cloud_coefficients_sw.nc
ln -sf ../rrtmgp-data/rrtmgp-clouds-lw.nc cloud_coefficients_lw.nc
ln -sf ../rrtmgp-data/rrtmgp-gas-sw-g224.nc coefficients_sw.nc
ln -sf ../rrtmgp-data/rrtmgp-gas-lw-g256.nc coefficients_lw.nc
ln -sf ../data/aerosol_optics.nc

# Translate DP-SCREAMXX output to RTE-RRTMGP-CPP input
DP_SCREAMXX_DIR=/projects/ml3drt
DP_SCREAMXX_RUN_NAME=scream_dpxx_RICO_doSW_05X05
DP_SCREAMXX_RUN_DIR=${DP_SCREAMXX_DIR}/${DP_SCREAMXX_RUN_NAME}/run
SCREAM_OUTPUT_FILE_BASE=scream.INSTANT.nhours_x1.2004-12-16-00000
SCREAM_OUTPUT_FILE_PATH=${DP_SCREAMXX_RUN_DIR}/${DP_SCREAMXX_RUN_NAME}.${SCREAM_OUTPUT_FILE_BASE}.nc
SCREAM_OUTPUT_FILE_PATH=${DP_SCREAMXX_RUN_DIR}/scream_dpxx_RICO_doSW.${SCREAM_OUTPUT_FILE_BASE}.nc

RTE_RRTMGP_DIR=/projects/ml3drt/rte_rrtmgp_cpp
RTE_RRTMGP_RUN_NAME=t_21_25
RTE_RRTMGP_RUN_DIR=${RTE_RRTMGP_DIR}/${DP_SCREAMXX_RUN_NAME}/${RTE_RRTMGP_RUN_NAME}
RTE_RRTMGP_INPUT_DIR=${RTE_RRTMGP_RUN_DIR}/input
RTE_RRTMGP_OUTPUT_DIR=${RTE_RRTMGP_RUN_DIR}/output
RTE_RRTMGP_VIZ_DIR=${RTE_RRTMGP_RUN_DIR}/viz
RTE_RRTMGP_VIZ_INPUT_DIR=${RTE_RRTMGP_VIZ_DIR}/input
RTE_RRTMGP_FILE_BASE=${DP_SCREAMXX_RUN_NAME}.${SCREAM_OUTPUT_FILE_BASE}
RTE_RRTMGP_INPUT_FILE_PATH_BASE=${RTE_RRTMGP_INPUT_DIR}/${RTE_RRTMGP_FILE_BASE}

mkdir -p ${RTE_RRTMGP_INPUT_DIR}
mkdir -p ${RTE_RRTMGP_OUTPUT_DIR}
mkdir -p ${RTE_RRTMGP_VIZ_DIR}

# Set SZAs, times, and coarsening factors
SZAS_PYTHON="[0, 85]"
COARSE_FACTORS_PYTHON="[1, 2]"
TIMES_PYTHON="[21, 22, 23, 24, 25]"
T0_PYTHON=-4
TF_PYTHON=-1

#python exp_hres/viz_tools/animate_dp_screamxx_output.py \
#    --dpscream_file_path ${SCREAM_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_VIZ_DIR}

#mpirun -np 2 python exp_hres/convert_dp_screamxx_output_new.py \
#    --dpscream_file_path ${SCREAM_OUTPUT_FILE_PATH} \
#    --rte_rrtmgp_cpp_dir_path ${RTE_RRTMGP_INPUT_DIR} \
#    --coarse_factors "${COARSE_FACTORS_PYTHON}" \
#    --szas "${SZAS_PYTHON}" \
#    --t0 "${T0_PYTHON}" --tf "${TF_PYTHON}"
#    #--times "${TIMES_PYTHON}" \

for FILE_NAME in ${RTE_RRTMGP_INPUT_DIR}/*;
do
  ln -sf ${FILE_NAME} rte_rrtmgp_input.nc
# Run RTE-RRTMGP-CPP
# Flags:
# --shortwave          DEFAULT[true]  : Enable computation of shortwave radiation.
# --longwave           DEFAULT[false] : Enable computation of longwave radiation.
# --fluxes             DEFAULT[true]  : Enable computation of fluxes.
# --two-stream         DEFAULT[true]  : Run two-stream solver to obtain 1D fluxes.
# --raytracing         DEFAULT[32]    : Ray tracer rays-per pixel. '--raytracing False' to turn off.
# --independent-column DEFAULT[false] : Run ray tracer in independent column mode.
# --cloud-optics       DEFAULT[false] : Enable cloud optics (both liquid and ice).
# --liq-cloud-optics   DEFAULT[false] : Liquid only cloud optics.
# --ice-cloud-optics   DEFAULT[false] : Ice only cloud optics.
# --cloud-mie          DEFAULT[false] : Use Mie tables for cloud scattering in ray tracer.
# --aerosol-optics     DEFAULT[false] : Enable aerosol optics.
# --single-gpt         DEFAULT[false] : Output optical properties and fluxes for a single g-point. '--single-gpt 100': output 100th g-point.
# --profiling          DEFAULT[false] : Perform additional profiling run.
# --delta-cloud        DEFAULT[false] : Delta-scaling of cloud optical properties.
# --delta-aerosol      DEFAULT[false] : Delta-scaling of aerosol optical properties.
# --tica               DEFAULT[false] : Attenuate path when doing an overhead 1D calculation of tilted input.
  ../build/test_rte_rrtmgp_rt_gpu --cloud-optics --raytracing 512
  RTE_RRTMGP_OUTPUT_FILE_PATH=${RTE_RRTMGP_OUTPUT_DIR}/$(basename ${FILE_NAME} .in.nc).out.nc 
  mv rte_rrtmgp_output.nc ${RTE_RRTMGP_OUTPUT_FILE_PATH}
done

#mpirun -np 4 python exp_hres/viz_tools/plot_input.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_VIZ_DIR}
mpirun -np 4 python exp_hres/viz_tools/plot_output.py \
    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_INPUT_DIR} \
    --rte_rrtmgp_cpp_output_dir_path ${RTE_RRTMGP_OUTPUT_DIR} \
    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_VIZ_DIR}
#mpirun -np 4 python exp_hres/viz_tools/plot_comparison.py \
#    --rte_rrtmgp_cpp_input_dir_path ${RTE_RRTMGP_INPUT_DIR} \
#    --rte_rrtmgp_cpp_output_dir_path ${RTE_RRTMGP_OUTPUT_DIR} \
#    --rte_rrtmgp_cpp_viz_dir_path ${RTE_RRTMGP_VIZ_DIR}